# Generated by Django 4.1.4 on 2023-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namex', models.CharField(max_length=250)),
                ('imgx', models.ImageField(upload_to='pics1')),
                ('descx', models.TextField()),
            ],
        ),
    ]
